app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='accueil'),
    path('inscription', views.register, name='inscription'),
    path('connexion', views.connexion, name='connexion'),
    path('restaurant/<id_resto>', views.resto_details, name='restaurant'),
    path('mon-espace/<username>', views.monespace, name='mon-espace'),
    path('deconnexion', views.deconnexion, name='deconnexion'),
    path('admin-resto/<username>', views.restolist, name='admin-resto'),
    path('admin-resto/create/<username>', views.createresto, name='create-resto'),
    path('admin-resto/<username>/<name>', views.adminReadResto, name='read-resto-admin'),
    path('admin-resto/update/<name>', views.adminReadResto, name='update-resto'),
]

foodaddict/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Profil(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)  # La liaison OneToOne vers le modèle User
    firstname= models.CharField(max_length = 128)
    lastname= models.CharField(max_length = 128)
    username = models.CharField(max_length = 128 , unique=True)
    address = models.CharField(max_length=512)
    postal_code = models.CharField(max_length=16)
    city = models.CharField(max_length=128)
    avatar = models.ImageField(null=True, blank=True, upload_to="static/avatars_user/")
    is_restaurateur = models.BooleanField()

    def __str__(self):
        return "Profil de {0}".format(self.user.username)


class Schedule(models.Model):
    day = models.CharField(max_length=16)
    opening_hour = models.TimeField()
    closing_hour = models.TimeField()

class Category(models.Model):
    label = models.CharField(max_length = 128)

class Ingredient(models.Model):
    name = models.CharField(max_length=128)

class Dish(models.Model):
    name = models.CharField(max_length=256)
    ingredients = models.ManyToManyField(Ingredient)
    price = models.FloatField()
    cat = models.ManyToManyField(Category)
    quantity = models.IntegerField()
    img = models.ImageField()

    class Meta:
        ordering = ['name']

class Restaurant(models.Model):
    mail = models.CharField(max_length=128)
    name = models.CharField(max_length=256)
    address = models.CharField(max_length=512)
    postal_code = models.CharField(max_length=16)
    city = models.CharField(max_length=128)
    owner = models.ForeignKey(User, on_delete=models.CASCADE) 
    image = models.ImageField(null=True, blank=True, upload_to="static/restaurant/")
    categories = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    dishes = models.ForeignKey(Dish, on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        ordering = ['name']

class Bookmark(models.Model):
    dish = models.ManyToManyField(Dish)
    restaurant = models.ManyToManyField(Restaurant)
    client = models.ManyToManyField(User)

class Order(models.Model):
    dishes = models.ManyToManyField(Dish)
    date = models.DateTimeField(default=timezone.now, verbose_name='Date de la commande')
    client = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ['date']

app/templates/restos/admin-restoread.html
{% extends "base.html" %}
{% block title %}Mon restaurant{% endblock %}
{% block nav %}
<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto" id="menufood">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'accueil' %}">Accueil</a>
    </li>
    {% if user.is_authenticated %}
    <li class="nav-item active">
      <a class="nav-link" href="{% url 'mon-espace' user.username %}">Mon espace<span
          class="sr-only">(current)</span></a>
    </li>
    {% endif %}
  </ul>
  <hr class="hr barbtn">
  {% if user.is_authenticated %}
  <div id="bouton_user">
    <b>{{ user.first_name }} {{user.last_name}}</b>
    <a class="ml-3" href="{% url 'deconnexion' %}">
      <button class="btn btn-danger my-2 mx-1 my-sm-0">Se déconnecter</button>
    </a>
  </div>
  {% else %}
  <div id="bouton_user">
    <a href="{% url 'connexion' %}">
      <button id="btn_connect" class="btn my-2 mx-1 my-sm-0">Se connecter</button>
    </a>
    <a href="{% url 'inscription' %}">
      <button id="btn_register" class="btn my-2 mx-1 my-sm-0">S'inscrire</button>
    </a>
  </div>
  {% endif %}
</div>
{% endblock %}

{% block content %}
<div class="container">
  <div class="bg-white rounded-lg shadow-lg m-5 p-2">
    <div class="text-center py-4 d-flex justify-content-around">
      <h1><i class="fas fa-store-alt mr-2" style="color: #36d085;"></i> <b>{{ resto.name }}</b></h1>
      <a href="../{{user.username}}">
        <button id="btn_register" class="btn btn-lg"><i class="fas fa-arrow-left mr-2"></i> Retour</button>
        </a>
      <a href="../{{user.username}}">
        <button class="btn btn-warning btn-lg"><i class="fas fa-pen mr-2"></i> Modifier</button>
        </a>
      <a href="../{{user.username}}">
        <button class="btn btn-danger btn-lg"><i class="fas fa-pen mr-2"></i> Supprimer</button>
        </a>
    </div>
    <div class="container">
    <table class="table text-center table-striped table-bordered table-sm">
      <thead class="thead-dark" >
        <tr>
          <th scope="col">Nom</th>
          <th scope="col">Adresse</th>
          <th scope="col">Code postal</th>
          <th scope="col">Ville</th>
          <th scope="col">Email</th>
          <th scope="col">Image</th>
          <th scope="col">Catégorie</th>
          <th scope="col">Plat</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th class="align-middle" scope="row">{{ resto.name }}</th>
          <td class="align-middle">{{ resto.address }}</td>
          <td class="align-middle">{{ resto.postal_code }}</td>
          <td class="align-middle">{{ resto.city }}</td>
          <td class="align-middle">{{ resto.mail }}</td>
          <td class="align-middle"><img src="../../{{ resto.image }}" class="img-thumbnail"></td>
          <td class="align-middle">{{ resto.categories }}</td>
          <td class="align-middle">{{ resto.dishes }}</td>
        </tr>
      </tbody>
    </table>
  </div>
  </div>
</div>
<div id="resto_bg"></div>
{% endblock %}
{% block footer %}
{% endblock %}

app/templates/restos/resto_details.html
{% extends 'base.html' %}
{% block title %}
	{{ restaurant.name }}
{% endblock %}
{% block content %}
	<div class="resto_img" style="background-image: url(../../{{ restaurant.image }})">
		<div class="resto_tag">
			<h1>{{ restaurant.name }}</h1>
			<p>{{ restaurant.address }}</p>
			<p>
				{{ restaurant.postal_code }}
				-
				{{ restaurant.city }}
			</p>
		</div>
	</div>
	<div class="container" id="container" style="margin-top: 5%">
		<div class="card-group px-3 d-flex justify-content-center">
			<div class="row">
				{% for dish in dishes %}
					<div class="col-sm-4">
						<div class="card" id="carteresto">
							<img id="imgcarte" class="card-img-top" src="../../static/dish/{{dish.img}}" alt="{{ dish.name }}">
							<div class="card-body text-center">
								<h5 class="card-title">{{ dish.name }}</h5>
                <p>{{ dish.price }}€</p>
							</div>
						</div>
					</div>
				{% endfor %}
			</div>
		</div>
	</div>
{% endblock %}

app/templates/restos/restocreate.html
{% extends "base.html" %}
{% block title %}Créer un restaurant{% endblock %}
{% block nav %}
<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto" id="menufood">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accueil' %}">Accueil</a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'mon-espace' user.username %}">Mon espace<span
            class="sr-only">(current)</span></a>
      </li>
      {% endif %}
    </ul>
    <hr class="hr barbtn">
    {% if user.is_authenticated %}
    <div id="bouton_user">
      <b>{{ user.first_name }} {{user.last_name}}</b>
      <a class="ml-3" href="{% url 'deconnexion' %}">
        <button class="btn btn-danger my-2 mx-1 my-sm-0">Se déconnecter</button>
      </a>
    </div>
    {% else %}
    <div id="bouton_user">
      <a href="{% url 'connexion' %}">
        <button id="btn_connect" class="btn my-2 mx-1 my-sm-0">Se connecter</button>
      </a>
      <a href="{% url 'inscription' %}">
        <button id="btn_register" class="btn my-2 mx-1 my-sm-0">S'inscrire</button>
      </a>
    </div>
    {% endif %}
  </div>
{% endblock %}
{% block content %}
<div class="container">
  <div class="container d-flex justify-content-center">
    <div id="container_form" class="shadow p-3 my-5 bg-white">
       <div class="text-center">
        <h1>Ajouter votre restaurant</h1>
        <hr class="hr">
       </div>
        <div class="d-flex justify-content-center pt-3">
        <form  enctype="multipart/form-data" method="post">
            {% csrf_token %}
            
        <div class="form-group">
          <label for="id_mail">Email de contact</label>
          <input type="mail" class="form-control" id="id_mail" name="mail" required>
        </div>
        <div class="form-group">
          <label for="id_name">Nom du restaurant</label>
          <input type="text" class="form-control" id="id_name" name="name" required>
        </div>
        <div class="form-group">
          <label for="id_address">Adresse</label>
          <input type="text" class="form-control" id="id_address" name="address" required>
        </div>
        <div class="form-group">
          <label for="id_postal_code">Code postal</label>
          <input type="text" class="form-control" id="id_postal_code" name="postal_code" required>
        </div>
        <div class="form-group">
          <label for="id_city">Ville</label>
          <input type="text" class="form-control" id="id_city" name="city" required>
        </div>
        <div class="form-group">
          <label for="id_image">Photo</label>
          <input type="file" class="form-control-file" id="id_image" accept="image/*" name="image">
        </div>
      
      
              <div class="text-center my-5">
                <button type="submit" id="btn_register" class="btn">Ajouter</button>
              </div>
        </form>
    </div>
    </div>
</div>
<div id="resto_bg"></div>
{% endblock %}
{% block footer %}
{% endblock %}

app/templates/restos/restolist.html
{% extends "base.html" %}
{% block title %}Mes restaurants{% endblock %}
{% block nav %}
<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto" id="menufood">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'accueil' %}">Accueil</a>
    </li>
    {% if user.is_authenticated %}
    <li class="nav-item active">
      <a class="nav-link" href="{% url 'mon-espace' user.username %}">Mon espace<span
          class="sr-only">(current)</span></a>
    </li>
    {% endif %}
  </ul>
  <hr class="hr barbtn">
  {% if user.is_authenticated %}
  <div id="bouton_user">
    <b>{{ user.first_name }} {{user.last_name}}</b>
    <a class="ml-3" href="{% url 'deconnexion' %}">
      <button class="btn btn-danger my-2 mx-1 my-sm-0">Se déconnecter</button>
    </a>
  </div>
  {% else %}
  <div id="bouton_user">
    <a href="{% url 'connexion' %}">
      <button id="btn_connect" class="btn my-2 mx-1 my-sm-0">Se connecter</button>
    </a>
    <a href="{% url 'inscription' %}">
      <button id="btn_register" class="btn my-2 mx-1 my-sm-0">S'inscrire</button>
    </a>
  </div>
  {% endif %}
</div>
{% endblock %}

{% block content %}
<div class="container">
  <div class="bg-white rounded-lg shadow-lg m-5 p-2">
    <div class="text-center py-4 d-flex justify-content-around">
      <h1><i class="fas fa-store-alt mr-2" style="color: #36d085;"></i> <b>Mes restaurants</b></h1>
      <a href="{% url 'create-resto' user.username %}">
        <button id="btn_register" class="btn btn-lg"><i class="fas fa-plus mr-2"></i> Ajouter un restaurant</button>
        </a>
    </div>
    <div class="container">
    <table class="table text-center table-striped table-bordered table-sm">
      <thead class="thead-dark" >
        <tr>
          <th scope="col">Nom</th>
          <th scope="col">Lieu</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
           {% for resto in restaurants %}
        <tr>
          <th class="align-middle" scope="row">{{ resto.name}}</th>
          <td class="align-middle">{{resto.city}}</td>
          <td class="align-middle">
              <a href="{% url 'read-resto-admin' user.username resto.name %}">
                  <button class="btn btn-primary"><i class="fas fa-eye"></i></button>
                </a>
                <a href="#">
                  <button class="btn btn-danger"><i class="fas fa-trash"></i></button>
                </a>
          </td>
        </tr>
        {% empty %}
        <tr>
          <th colspan="3">Vous n'avez renseigné aucun restaurant pour le moment !</th>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  {% if restaurants.has_other_pages %}
  <nav aria-label="Pagination" >
  <ul class="pagination justify-content-center">
    {% if restaurants.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ restaurants.previous_page_number }}">&laquo;</a></li>
    {% else %}
    <li class="page-item disabled"><a class="page-link" href="#">&laquo;</a></li>
    {% endif %}
    {% for i in restaurants.paginator.page_range %}
      {% if restaurants.number == i %}
      <li class="page-item active"><span class="page-link">
        {{ i }}
        <span class="sr-only">(current)</span>
      </span></li>
      {% else %}
      <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if restaurants.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ restaurants.next_page_number }}">&raquo;</a></li>
    {% else %}
    <li class="page-item disabled"><a class="page-link" href="#">&raquo;</a></li>
    {% endif %}
  </ul>
</nav>
{% endif %}
  </div>
</div>
<div id="resto_bg"></div>
{% endblock %}
{% block footer %}
{% endblock %}