app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='accueil'),
    path('inscription', views.register, name='inscription'),
    path('connexion', views.connexion, name='connexion'),
    path('restaurant/<id_resto>', views.resto_details, name='restaurant'),
    path('mon-espace/<username>', views.monespace, name='mon-espace'),
    path('deconnexion', views.deconnexion, name='deconnexion'),
    path('admin-resto/<username>', views.restolist, name='admin-resto'),
    path('admin-resto/create/<username>', views.createresto, name='create-resto'),
    path('admin-resto/<username>/<name>', views.adminReadResto, name='read-resto-admin'),
    path('admin-resto/update/<name>', views.adminReadResto, name='update-resto'),
]

foodaddict/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Profil(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)  # La liaison OneToOne vers le modèle User
    firstname= models.CharField(max_length = 128)
    lastname= models.CharField(max_length = 128)
    username = models.CharField(max_length = 128 , unique=True)
    address = models.CharField(max_length=512)
    postal_code = models.CharField(max_length=16)
    city = models.CharField(max_length=128)
    avatar = models.ImageField(null=True, blank=True, upload_to="static/avatars_user/")
    is_restaurateur = models.BooleanField()

    def __str__(self):
        return "Profil de {0}".format(self.user.username)


class Schedule(models.Model):
    day = models.CharField(max_length=16)
    opening_hour = models.TimeField()
    closing_hour = models.TimeField()

class Category(models.Model):
    label = models.CharField(max_length = 128)

class Ingredient(models.Model):
    name = models.CharField(max_length=128)

class Dish(models.Model):
    name = models.CharField(max_length=256)
    ingredients = models.ManyToManyField(Ingredient)
    price = models.FloatField()
    cat = models.ManyToManyField(Category)
    quantity = models.IntegerField()
    img = models.ImageField()

    class Meta:
        ordering = ['name']

class Restaurant(models.Model):
    mail = models.CharField(max_length=128)
    name = models.CharField(max_length=256)
    address = models.CharField(max_length=512)
    postal_code = models.CharField(max_length=16)
    city = models.CharField(max_length=128)
    owner = models.ForeignKey(User, on_delete=models.CASCADE) 
    image = models.ImageField(null=True, blank=True, upload_to="static/restaurant/")
    categories = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    dishes = models.ForeignKey(Dish, on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        ordering = ['name']

class Bookmark(models.Model):
    dish = models.ManyToManyField(Dish)
    restaurant = models.ManyToManyField(Restaurant)
    client = models.ManyToManyField(User)

class Order(models.Model):
    dishes = models.ManyToManyField(Dish)
    date = models.DateTimeField(default=timezone.now, verbose_name='Date de la commande')
    client = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ['date']

app/templates/home.html
{% extends "base.html" %}
{% block title %}FoodAddict
{% endblock %}
{% block content %}
	<div class="container" id="container">
		<div id="block_search">
			<div id="formulaire">
				<p id="title">
					<b><i class="fas fa-utensils mr-2" style="color: #36d085;"></i> <i>So Fast ! So Good !</i></b>
				</p>
				<p class="text-muted">FoodAddict est une façon facile de vous faire livrer vos repas préférés.</p>
			</div>
			<div id="cuisto">
				{% load static %}
				<img class="responsive" src="{% static 'img/cuisto.gif' %}"/>
			</div>
		</div>
	</div>

	<div id="bg_section">
		<div class="text-center py-5">
			<h1 class="text-white">
				<i class="fas fa-utensils mr-2"></i>
				<b>Tous les restaurants</b>
			</h1>
		</div>
		<div class="card-group px-3 d-flex justify-content-center">
			<div class="row">
				{% for resto in restaurants %}
					<div class="col-sm-4">
						<a href="restaurant/{{ resto.id }}">
							<div class="card" id="carteresto">
								<img id="imgcarte" class="card-img-top" src="../../{{resto.image}}" alt="{{ resto.name }}">
								<div class="card-body text-center">
									<h5 class="card-title">{{ resto.name }}</h5>
									<p class="card-text">
										<small>{{ resto.city }}</small>
									</p>
								</div>
							</div>
						</a>
					</div>
				{% endfor %}
			</div>
		</div>
		{% if restaurants.has_other_pages %}
			<nav aria-label="Pagination">
				<ul class="pagination justify-content-center mt-5">
					{% if restaurants.has_previous %}
						<li class="page-item">
							<a class="page-link" href="?page={{ restaurants.previous_page_number }}#bg_section">&laquo;</a>
						</li>
					{% else %}
						<li class="page-item disabled">
							<a class="page-link" href="#">&laquo;</a>
						</li>
					{% endif %}
					{% for i in restaurants.paginator.page_range %}
						{% if restaurants.number == i %}
							<li class="page-item active">
								<span class="page-link">
									{{ i }}
									<span class="sr-only">(current)</span>
								</span>
							</li>
						{% else %}
							<li class="page-item">
								<a class="page-link" href="?page={{ i }}#bg_section">{{ i }}</a>
							</li>
						{% endif %}
					{% endfor %}
					{% if restaurants.has_next %}
						<li class="page-item">
							<a class="page-link" href="?page={{ restaurants.next_page_number }}#bg_section">&raquo;</a>
						</li>
					{% else %}
						<li class="page-item disabled">
							<a class="page-link" href="#">&raquo;</a>
						</li>
					{% endif %}
				</ul>
			</nav>
		{% endif %}
	</div>
</div>{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% block title %}Connexion{% endblock %}
{% block nav %}
<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto" id="menufood">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'accueil' %}">Accueil</a>
    </li>
    {% if user.is_authenticated %}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'mon-espace' user.username %}">Mon espace<span class="sr-only">(current)</span></a>
    </li>
    {% endif %}
  </ul>
  <hr class="hr barbtn">
  {% if user.is_authenticated %}
  <div id="bouton_user">
    <b>{{ user.first_name }} {{user.last_name}}</b>
    <a class="ml-3" href="{% url 'deconnexion' %}">
    <button class="btn btn-danger my-2 mx-1 my-sm-0">Se déconnecter</button>
    </a>
  </div>
            {% else %}
  <div id="bouton_user">
    <a href="{% url 'connexion' %}">
    <button id="btn_connect" class="btn my-2 mx-1 my-sm-0">Se connecter</button>
    </a>
    <a href="{% url 'inscription' %}">
    <button id="btn_register" class="btn my-2 mx-1 my-sm-0">S'inscrire</button>
    </a>
  </div>
  {% endif %}
</div>
{% endblock %}
{% block content %}
    <div id="container_p_login" class="container d-flex justify-content-center">
        <div id="container_form" class="shadow p-3 my-5 bg-white">
           <div class="text-center">
            <h1>Se connecter</h1>
            <hr class="hr">
           </div>
            <div id="form_login" class="pt-3">
              {% if user.is_authenticated %}
                Vous êtes connecté, {{ user.username }} !
            {% else %}
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username"><i class="fas fa-user mr-2"></i> Identifiant</label>
                    <input type="text" class="form-control" id="username" name="username">
                  </div>
                  <div class="form-group">
                    <label for="InputPassword"><i class="fas fa-key mr-2"></i> Mot de passe</label>
                    <input type="password" class="form-control" id="InputPassword" name="password">
                  </div>
                  <div class="text-center my-5">
                    <button type="submit" id="btn_register" class="btn">Je me connecte</button>
                  </div>
            </form>
            {% endif %}
        </div>
        </div>
    </div>
    <div id="hamburger_register"></div>
    <div id="salon_register"></div>
{% endblock %}

{% block footer %}
    
    {% endblock %}

app/templates/monespace.html
{% extends "base.html" %}
{% block title %}Mon espace{% endblock %}
{% block nav %}
<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto" id="menufood">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'accueil' %}">Accueil</a>
    </li>
    {% if user.is_authenticated %}
    <li class="nav-item active">
      <a class="nav-link" href="{% url 'mon-espace' user.username %}">Mon espace<span
          class="sr-only">(current)</span></a>
    </li>
    {% endif %}
  </ul>
  <hr class="hr barbtn">
  {% if user.is_authenticated %}
  <div id="bouton_user">
    <b>{{ user.first_name }} {{user.last_name}}</b>
    <a class="ml-3" href="{% url 'deconnexion' %}">
      <button class="btn btn-danger my-2 mx-1 my-sm-0">Se déconnecter</button>
    </a>
  </div>
  {% else %}
  <div id="bouton_user">
    <a href="{% url 'connexion' %}">
      <button id="btn_connect" class="btn my-2 mx-1 my-sm-0">Se connecter</button>
    </a>
    <a href="{% url 'inscription' %}">
      <button id="btn_register" class="btn my-2 mx-1 my-sm-0">S'inscrire</button>
    </a>
  </div>
  {% endif %}
</div>
{% endblock %}
{% block content %}
<div class="container">
  <div id="profile" class="bg-white rounded-lg shadow-lg mt-5 d-flex justify-content-around align-items-center">
    <div id="presentation" class="text-center">
      {% load static %}
      <img src="../../{{profil.avatar}}" id="imgprofile" class="img-fluid rounded-circle" alt="Image profil">
      <h4 class="mt-3 font-weight-bold">{{ profil.firstname }} {{ profil.lastname }}</h4>
      {% if user.is_superuser %}
      <h5 class="text-secondary">Administrateur</h5>
      {% elif profil.is_restaurateur %}
      <h5 class="text-secondary">Restaurateur</h5>
      {% else %}
      <h5 class="text-secondary">Client</h5>
      {% endif %}
    </div>
    <div id="barrevt"></div>
    <div>
      <div class="text-center mb-5">
        <h1><b>Mon espace</b></h1>
      </div>
      <div class="d-flex align-self-center">
        <div id="commandes" >
          <div class="text-center">
            <h5 class="mb-4"><i class="fas fa-utensils mr-2" style="color: #36d085;"></i><b> Mes commandes</b></h5>
          </div>
          <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Plat</th>
                <th scope="col">Date</th>
              </tr>
            </thead>
            <tbody>
              {% for order in orders %}
                  <tr>
                    <th scope="row">{{ order.id }}</th>
                    <td>{{ order.dishes.name }}</td>
                    <td>{{ order.date }}</td>
                  </tr>
                {% empty %}
                  <tr>
                    <th colspan="3">Pas encore de commande !</th>
                  </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
      {% if profil.is_restaurateur %}
      <div class="d-flex justify-content-center mt-3">
        <a href="{% url 'admin-resto' user.username %}">
          <button id="btn_register" class="btn">Gérer mes restaurants</button>
          </a>
      </div>
      {% endif %}
    </div>

  </div>
</div>
<div id="chef_bg"></div>
{% endblock %}
{% block footer %}
{% endblock %}

app/templates/register.html
{% extends "base.html" %}
{% block title %}Inscription{% endblock %}
{% block nav %}
<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto" id="menufood">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'accueil' %}">Accueil</a>
    </li>
    {% if user.is_authenticated %}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'mon-espace' user.username %}">Mon espace<span class="sr-only">(current)</span></a>
    </li>
    {% endif %}
  </ul>
  <hr class="hr barbtn">
  {% if user.is_authenticated %}
  <div id="bouton_user">
    <b>{{ user.first_name }} {{user.last_name}}</b>
    <a class="ml-3" href="{% url 'deconnexion' %}">
    <button class="btn btn-danger my-2 mx-1 my-sm-0">Se déconnecter</button>
    </a>
  </div>
            {% else %}
  <div id="bouton_user">
    <a href="{% url 'connexion' %}">
    <button id="btn_connect" class="btn my-2 mx-1 my-sm-0">Se connecter</button>
    </a>
    <a href="{% url 'inscription' %}">
    <button id="btn_register" class="btn my-2 mx-1 my-sm-0">S'inscrire</button>
    </a>
  </div>
  {% endif %}
</div>
{% endblock %}
{% block content %}
    
    <div class="container d-flex justify-content-center">
        <div id="container_form" class="shadow p-3 my-5 bg-white">
           <div class="text-center">
            <h1>S'inscrire</h1>
            <hr class="hr">
           </div>
            <div class="d-flex justify-content-center pt-3">
            <form  enctype="multipart/form-data" method="post">
                {% csrf_token %}
                
          <div class="form-group">
            <label for="id_username"><i class="fas fa-user mr-2"></i> Nom d'utilisateur</label>
            <input type="text" class="form-control" id="id_username" aria-describedby="usernameHelp" name="username" maxlength="150" required>
            <small id="usernameHelp" class="form-text text-muted">Requis. 150 caractères maximum. Uniquement des lettres, nombres et les caractères « @ », « . », « + », « - » et « _ »..</small>
          </div>
          <div class="form-group">
            <label for="id_password"><i class="fas fa-key mr-2"></i> Mot de passe</label>
            <input type="password" class="form-control" id="id_password" aria-describedby="passwordHelp" name="password" required>
            <small id="passwordHelp" class="form-text text-muted">Votre mot de passe ne peut pas trop ressembler à vos autres informations personnelles.<br />
              Votre mot de passe doit contenir au minimum 8 caractères.<br />
              Votre mot de passe ne peut pas être un mot de passe couramment utilisé.<br />
              Votre mot de passe ne peut pas être entièrement numérique.</small>
          </div>
          <div class="form-group">
            <label for="id_email"><i class="fas fa-envelope mr-2"></i> Email</label>
            <input type="email" class="form-control" id="id_email" maxlength="254" name="email" required>
          </div>
          <div class="form-group">
            <label for="id_firstanme">Prénom</label>
            <input type="text" class="form-control" id="id_firstanme" name="firstname" maxlength="128" required>
          </div>
          <div class="form-group">
            <label for="id_lastname">Nom</label>
            <input type="text" class="form-control" id="id_lastname" name="lastname" maxlength="128" required>
          </div>
          <div class="form-group">
            <label for="id_address">Adresse</label>
            <input type="text" class="form-control" id="id_address" name="address" maxlength="512" required>
          </div>
          <div class="form-group">
            <label for="id_postal_code">Code postal</label>
            <input type="text" class="form-control" id="id_postal_code" name="postal_code" maxlength="16" required>
          </div>
          <div class="form-group">
            <label for="id_city">Ville</label>
            <input type="text" class="form-control" id="id_city" name="city" maxlength="128" required>
          </div>
          <div class="form-group">
            <label for="id_avatar">Photo de profil</label>
            <input type="file" class="form-control-file" id="id_avatar" accept="image/*" name="avatar">
          </div>
          <div class="form-check mt-5">
            <input class="form-check-input" type="checkbox" id="id_is_restaurateur" name="is_restaurateur">
            <label class="form-check-label" for="id_is_restaurateur">
              Vous êtes restaurateur ?
            </label>
          </div>
                  <div class="text-center my-5">
                    <button type="submit" id="btn_register" class="btn">Je m'inscris</button>
                  </div>
            </form>
        </div>
        </div>
    </div>
    <div id="hamburger_register"></div>
    <div id="salon_register"></div>
{% endblock %}

{% block footer %}
    
    {% endblock %}